# Generated by Django 2.2.7 on 2021-07-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210709_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('education_details', models.CharField(max_length=50)),
                ('linkedin_url', models.CharField(blank=True, max_length=50)),
                ('add_info', models.TextField(blank=True)),
            ],
        ),
    ]
